"""
DTC phrase library — organized by vertical.
Each phrase is crafted to appear in actual DTC ad copy,
specific enough to avoid big-box retailers dominating results.
"""

DTC_PHRASES: dict[str, list[str]] = {
    "beauty": [
        "hyaluronic serum shop now",
        "cruelty free skincare",
        "clean beauty brand",
        "dermatologist tested moisturizer",
        "vitamin c serum free shipping",
        "retinol cream anti aging",
        "niacinamide toner",
        "natural skincare routine",
        "spf moisturizer daily",
        "glow serum try risk free",
        "face mask subscription",
        "clean makeup brand",
    ],
    "supplements": [
        "gut health supplement",
        "third party tested protein",
        "clinically studied formula",
        "non-gmo vitamin",
        "collagen peptides shop now",
        "ashwagandha stress relief",
        "probiotic daily supplement",
        "omega 3 free shipping",
        "magnesium sleep supplement",
        "energy boost formula",
        "greens powder daily",
        "mushroom supplement focus",
    ],
    "fashion": [
        "sustainable fashion brand",
        "ethically made clothing",
        "elevated basics shop now",
        "organic cotton tee",
        "slow fashion brand",
        "minimalist wardrobe essentials",
        "streetwear brand drop",
        "premium denim brand",
        "activewear shop now",
        "loungewear free shipping",
        "linen clothing brand",
        "capsule wardrobe essentials",
    ],
    "accessories": [
        "genuine leather belt",
        "full grain leather belt",
        "handcrafted leather belt",
        "mens leather belt free shipping",
        "designer belt buckle",
        "leather wallet shop now",
        "minimalist wallet slim",
        "canvas belt shop now",
        "leather goods brand",
        "belt shop try now",
        "braided belt women",
        "reversible leather belt",
    ],
    "food_beverage": [
        "small batch coffee roasters",
        "organic matcha shop now",
        "keto snacks free shipping",
        "clean protein bar",
        "grass fed beef jerky",
        "cold brew coffee subscription",
        "functional mushroom coffee",
        "clean energy drink",
        "gut health drinks",
        "adaptogen blend",
        "non gmo granola",
        "raw honey shop now",
    ],
    "fitness": [
        "home workout equipment",
        "resistance bands set",
        "adjustable dumbbells shop",
        "premium yoga mat",
        "kettlebell home gym",
        "foam roller recovery",
        "pull up bar doorway",
        "jump rope fitness",
        "ab roller workout",
        "home gym equipment free shipping",
        "pilates equipment shop",
        "exercise bike compact",
    ],
    "pet": [
        "grain free dog food",
        "natural dog treats shop",
        "vet recommended dog food",
        "raw dog food delivery",
        "cat food subscription",
        "dog hip joint supplement",
        "natural pet grooming",
        "personalized dog collar",
        "cat toy subscription box",
        "orthopedic dog bed",
        "freeze dried dog food",
        "pet cbd oil",
    ],
    "home": [
        "non-toxic soy candle",
        "linen bedding shop now",
        "organic bamboo sheets",
        "natural cleaning products",
        "essential oil diffuser",
        "weighted blanket shop",
        "minimalist home decor",
        "ceramic cookware set",
        "beeswax candle handmade",
        "sustainable home goods",
        "reusable kitchen products",
        "zero waste home",
    ],
    "tech_gadgets": [
        "wireless earbuds shop now",
        "portable charger fast",
        "blue light glasses shop",
        "standing desk converter",
        "mechanical keyboard compact",
        "ergonomic laptop stand",
        "ring light creator",
        "fitness tracker watch",
        "smart home gadget",
        "noise cancelling earbuds",
        "phone case brand shop",
        "usb c hub shop now",
    ],
    "baby_kids": [
        "organic baby clothes",
        "non-toxic baby toys",
        "montessori toys shop",
        "natural baby skincare",
        "reusable diaper brand",
        "wooden toys handmade",
        "educational toys subscription",
        "ergonomic baby carrier",
        "toddler learning toys",
        "organic baby formula",
        "baby sleep sack shop",
        "sensory toys toddler",
    ],
}

ALL_VERTICALS = list(DTC_PHRASES.keys())


def get_phrases(verticals: list[str] | None = None) -> list[str]:
    """Return flat list of phrases for given verticals (or all if None)."""
    targets = verticals if verticals else ALL_VERTICALS
    out = []
    for v in targets:
        out.extend(DTC_PHRASES.get(v, []))
    return out
